<div class="table-responsive">
    <table class="table table-striped table-bordered" id="DTable" data-page-length='100' data-name="Search_epin_list" data-export='Yes'>
        <thead>
        <tr>
            <th>SN</th>
            <th>Epin</th>
            <th>Amount</th>
            <th>Generated By</th>
            <th>Issued To</th>
            <th>Transferred By</th>
            <th>Used By</th>
            <th class="datefilter">Used Date</th>
            <th class="noExport">Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $sn = 1;
        foreach ($epin as $e) { ?>
            <tr>
                <td><?php echo $sn++; ?></td>
                <td><?php echo $e['epin']; ?></td>
                <td><?php echo $e['amount']; ?></td>
                <td><?php echo $e['generated_by']; ?></td>
                <td><?php echo $e['issue_to'] ? config_item('ID_EXT') . $e['issue_to'] : ''; ?></td>
                <td><?php echo $e['transfer_by'] ? config_item('ID_EXT') . $e['transfer_by'] : ''; ?></td>
                <td><?php echo $e['used_by'] ? config_item('ID_EXT') . $e['used_by'] : ''; ?></td>
                <td><?php echo $e['used_time']; ?></td>
                <?php if($e['used_by'] =='') { ?>
                <td>
                    <div style="display: flex;">
                    <a href="<?php echo site_url('admin/epin/edit/' . $e['id']); ?>"
                       class="btn btn-info btn-sm mr-1">Edit</a>
                    <a onclick="return confirm('Are you sure you want to delete this epin ?')"
                       href="<?php echo site_url('admin/epin/remove/' . $e['id']); ?>" class="btn btn-danger btn-sm">Delete</a>
                          </div>
                </td>
                <?php } else { ?>
                <td></td>
                <?php } ?>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<div class="pull-right">
    <?php echo $this->pagination->create_links(); ?>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        document.getElementsByClassName('active')[0].classList.remove('active');
        document.getElementById("epin").classList.add('active');
        document.querySelector("#epin > ul > li:nth-child(4) > a > span").setAttribute('style', 'color: darkorange !important;');
    });
</script>